
- name: Install the OpenvSwitch Package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - openstack-neutron-openvswitch
  - libibverbs

- name: Enable and Start the OpenvSwitch Service
  service:
    name: openvswitch
    state: started
    enabled: yes

- name: Creating a OVS Bridge
  shell: ovs-vsctl add-br br-ex

- name: Verify the OVS Bridge is created or not
  shell: ovs-vsctl show
  register: result

- debug:
    var: result.stdout

- name: Network Configuration for the {{ device_name }}
  template:
    src: ifcfg-eth0.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ device_name }}"
    backup: yes

- name: Network Configuration for the OVS Bridge
  template:
    src: ifcfg-br-ex.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-br-ex"

- name: Adding sysctl entries "net.ipv4.ip_forward"
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Adding sysctl entries "net.ipv4.conf.all.rp_filter"
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: Adding sysctl entries "net.ipv4.conf.default.rp_filter"
  sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: Adding the OVS Bridge ( br-ex ) to the interface ( {{ device_name }} )
  shell: ovs-vsctl add-port br-ex {{ device_name }}

- name: reboot
  reboot:
    reboot_timeout: 100

- name: wait for nodes to come up
  wait_for_connection:
    delay: 30
    timeout: 30
